server:
  port: 8080

spring:
  application:
    name: ms-rufe

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  transaction:
    rollback-on-error: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: co.rufe.rufe

application:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

logging:
  level:
    com.rufe: INFO
    org.springframework: WARN
    org.springframework.jdbc.core: DEBUG
    org.springframework.security: DEBUG

app:
  dataloader:
    enabled: ${APP_DATALOADER_ENABLED:false}
